# Generated by Django 5.2.5 on 2025-08-13 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_receitas_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receitas',
            name='autor',
        ),
        migrations.AddField(
            model_name='receitas',
            name='ingrediente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='receitas.ingredientes'),
        ),
    ]
