# Generated by Django 5.2.6 on 2025-09-03 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_remove_receitas_autor_receitas_ingrediente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receitas',
            name='ingrediente',
        ),
        migrations.CreateModel(
            name='IngredienteReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.ingredientes')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.receitas')),
            ],
        ),
        migrations.AddField(
            model_name='receitas',
            name='ingredientes',
            field=models.ManyToManyField(related_name='receitas', through='receitas.IngredienteReceita', through_fields=('receita', 'ingrediente'), to='receitas.ingredientes'),
        ),
    ]
